[env:esp32dev]
platform = espressif32
board = nodemcu-32s
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bblanchon/ArduinoJson @ ^7.0.0